### ISSUE TITLE
TypeError: Headers is not a constructor

### ISSUE THREAD

**Issue by tiagosiebler** [sindresorhus/ky#141]
I've had a somewhat frustrating start to ky, not sure what I'm doing wrong

```
(node:29176) UnhandledPromiseRejectionWarning: TypeError: Headers is not a constructor
    at new Ky (/Volumes/Repositories/Private/apitests/testProj1/node_modules/ky/umd.js:211:20)
    at Function.ky.(anonymous function) [as get] (/Volumes/Repositories/Private/apitests/testProj1/node_modules/ky/umd.js:389:37)
    at getParentChildEndpoint (/Volumes/Repositories/Private/apitests/testProj1/src/api/util/getParentChildEndpoint.js:14:16)
    at Object.getStatus (/Volumes/Repositories/Private/apitests/testProj1/src/api/instanceApi.js:49:22)
```

Rerproduced like this:
```
const ky = require('ky-universal').default;

const prefix = 'http://aa9da6ff.ngrok.io/api/instances/gub6r';
const instanceApi = ky.create({ prefixUrl: prefix, throwHttpErrors: false });
const result = await instanceApi.get('status').json();
```

This seems to be line 211 in umd.js:
![Screenshot 2019-06-17 at 11 15 57](https://user-images.githubusercontent.com/14090872/59597278-50492600-90f1-11e9-9e5c-b8972feb86a2.png)

I have both KY and Ky-universal installed. What am I doing wrong or missing? 

If I try to catch this, the error is the same as that shown in the stack trace. I'd expect a HTTP error (like 404), not a stack trace like this. Thanks!

**Comment by tiagosiebler** [comment]
Weird, seems to work if I add a line here:
https://github.com/sindresorhus/ky-universal/blob/master/index.js#L17

```
if (!global.fetch) {
	global.fetch = fetch;
	global.Headers = fetch.Headers;
	global.Response = fetch.Response;
	global.AbortController = AbortController;
}

global.Headers = global.fetch.Headers;

const {
	default: ky,
	HTTPError,
	TimeoutError
} = require('ky/umd');
```

**Comment by sholladay** [comment]
My guess is that this is somehow caused by `ky-universal` overwriting `global.Headers` without checking if it exists first. Maybe `fetch.Headers` is not a constructor? If it's not, then that's going to be a problem.

**Comment by szmarczak** [comment]
I could not reproduce this.

> Weird, seems to work if I add a line here:

Instead add `console.log(global.Headers)` and paste the output here.
If it's `undefined`, do `console.log(global.fetch)`.

**Comment by tiagosiebler** [comment]
@szmarczak Thanks for helping. global.Headers is indeed `undefined`. Here's both console logs:
```
undefined
{ [Function: fetch]
  isRedirect: [Function],
  Promise: [Function: Promise],
  default: [Circular],
  Headers: [Function: Headers],
  Request: [Function: Request],
  Response: [Function: Response],
  FetchError: [Function: FetchError] }
```

A really lazy fix has been to change that if condition instead of the global.fetch check:
```
if (!global.Headers) {
```

In case it matters, this is with node 10.15.1. Local machine and remote server see the same behaviour.

**Comment by szmarczak** [comment]
What about putting `console.log` here:

```js
if (!global.fetch) {
	global.fetch = fetch;
	global.Headers = fetch.Headers;
        console.log(global.Headers, Headers, fetch);
	global.Response = fetch.Response;
	global.AbortController = AbortController;
}
```

**Comment by szmarczak** [comment]
The first part and the second part should be the same. If not, it's a really weird bug. The third part should be the fetch object.

**Comment by tiagosiebler** [comment]
That returns an immediate exception, since headers is undefined in node:
```
/node_modules/ky-universal/index.js:11
console.log(global.fetch, global.Headers, Headers, fetch);
                                          ^

ReferenceError: Headers is not defined
```

Interestingly:
- global.fetch is always defined, so this if condition is never used in node
- global.Headers is undefined
- fetch is defined

A simple workaround is ensure global.Headers = global.fetch.Headers, the if condition itself isn't needed in this case. Not sure what the context is to Headers vs global.fetch, given that finding...

**Comment by szmarczak** [comment]
Try:

```js
if (!global.fetch) {
	global.fetch = fetch;
	global.Headers = fetch.Headers;
        console.log(global.Headers, fetch.Headers, fetch);
	global.Response = fetch.Response;
	global.AbortController = AbortController;
}

**Comment by tiagosiebler** [comment]
The if block is never executed, because global.fetch is defined

**Comment by szmarczak** [comment]
Problem solved. Something defines `global.fetch` before we do. We need to use a symbol instead `if (!global.fetch)`
