### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by MoonFoxy** [sindresorhus/ky#281]
```D:\GitHub\Narmaya_DBot\node_modules\ky\index.js:523
export default createInstance();
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:991:16)
    at Module._compile (internal/modules/cjs/loader.js:1039:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (d:\GitHub\Narmaya_DBot\source\commands\info\weather.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
```

This error crashes when
```js
const ky= require('ky');
```
I am using NodeJS 14.9.0

**Comment by MoonFoxy** [comment]
Ohh sorry i know whats wrong
