### ISSUE TITLE
Ky's types don't work in Deno's Typescript

### ISSUE THREAD

**Issue by Xeoth** [sindresorhus/ky#294]
The types that Ky provides are in compatible with Deno's Typescript and cause duplicate identifier errors:

```ts
TS2300 [ERROR]: Duplicate identifier 'TextEncoder'.
declare class TextEncoder {
              ~~~~~~~~~~~
    at asset:///lib.deno.web.d.ts:179:15

    'TextEncoder' was also declared here.
    interface TextEncoder extends TextEncoderCommon {
              ~~~~~~~~~~~
        at asset:///lib.dom.d.ts:15504:11    and here.
    declare var TextEncoder: {
                ~~~~~~~~~~~
        at asset:///lib.dom.d.ts:15515:13

TS2300 [ERROR]: Duplicate identifier 'AbortController'.
declare class AbortController {
              ~~~~~~~~~~~~~~~
    at asset:///lib.deno.web.d.ts:193:15

    'AbortController' was also declared here.
    interface AbortController {
              ~~~~~~~~~~~~~~~
        at asset:///lib.dom.d.ts:1939:11    and here.
    declare var AbortController: {
                ~~~~~~~~~~~~~~~
        at asset:///lib.dom.d.ts:1950:13
 ```

Someone in Deno's Discord server suggested that removing `/// <reference lib="dom"/>` from index.d.ts would help.

**Comment by sholladay** [comment]
I think this is basically the same as https://github.com/sindresorhus/ky/issues/224, although the use case and error messages are different.

The proposed fix looks simple, though I'd like a TyoeScript expert to weigh in on it. Want to open a PR to get the ball rolling? Should include updated documentation.
