### ISSUE TITLE
Ky 0.31.2 fails on NodeJS 18.7.0

### ISSUE THREAD

**Issue by yannick-aivayan** [sindresorhus/ky#452]
Since the addition of `supportsReadableStream` into `ky/distribution/core/constants.js` I have a `TypeError [ERR_INVALID_URL]: Invalid URL`

`new globalThis.Request('')` throws (since the request param is indeed an empty string)

Not sure how to fix that since since it's related to https://github.com/sindresorhus/ky/issues/450

Error details:

```log
TypeError: Failed to parse URL from
    at new Request (node:internal/deps/undici/undici:5446:19)
    at file:///Users/me/Sites/my-site/node_modules/.pnpm/ky@0.31.2/node_modules/ky/distribution/core/constants.js:8:30
    ... 24 lines matching cause stack trace ...
    at async file:///Users/me/Sites/my-site/node_modules/.pnpm/tinypool@0.2.4/node_modules/tinypool/dist/esm/worker.js:99:20 {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:387:5)
      at URL.onParseError (node:internal/url:564:9)
      at new URL (node:internal/url:644:5)
      at new Request (node:internal/deps/undici/undici:5444:25)
      at file:///Users/me/Sites/my-site/node_modules/.pnpm/ky@0.31.2/node_modules/ky/distribution/core/constants.js:8:30
      at file:///Users/me/Sites/my-site/node_modules/.pnpm/ky@0.31.2/node_modules/ky/distribution/core/constants.js:22:3
      at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
      at async Promise.all (index 0)
      at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
      at async VitestRunner.interopedImport (file:///Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-vite-node-client.cddda63d.mjs:233:17)
      at async VitestRunner.directRequest (file:///Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-vite-node-client.cddda63d.mjs:159:24)
      at async VitestRunner.cachedRequest (file:///Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-vite-node-client.cddda63d.mjs:112:12)
      at async _VitestMocker.request (file:///Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-vite-node-client.cddda63d.mjs:135:16)
      at async /Users/me/Sites/my-site/modular-app/src/core/composables/use-user.ts:5:31
      at async VitestRunner.directRequest (file:///Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-vite-node-client.cddda63d.mjs:216:5)
      at async VitestRunner.cachedRequest (file:///Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-vite-node-client.cddda63d.mjs:112:12)
      at async _VitestMocker.request (file:///Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-vite-node-client.cddda63d.mjs:135:16)
      at async /Users/me/Sites/my-site/modular-app/vitest-setup/connect-user.ts:7:31
      at async VitestRunner.directRequest (file:///Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-vite-node-client.cddda63d.mjs:216:5)
      at async VitestRunner.cachedRequest (file:///Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-vite-node-client.cddda63d.mjs:112:12)
      at async _VitestMocker.request (file:///Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-vite-node-client.cddda63d.mjs:135:16)
      at async /Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-runtime-error.1104e45a.mjs:268:5
      at async Promise.all (index 7)
      at async runSetupFiles (/Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-runtime-error.1104e45a.mjs:266:3)
      at async collectTests (/Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-runtime-error.1104e45a.mjs:308:7)
      at async startTestsNode (/Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-runtime-error.1104e45a.mjs:634:17)
      at async /Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/entry.mjs:76:9
      at async Module.withEnv (/Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/chunk-runtime-error.1104e45a.mjs:259:5)
      at async run (/Users/me/Sites/my-site/node_modules/.pnpm/vitest@0.22.1_happy-dom@6.0.4/node_modules/vitest/dist/entry.mjs:71:5)
      at async file:///Users/me/Sites/my-site/node_modules/.pnpm/tinypool@0.2.4/node_modules/tinypool/dist/esm/worker.js:99:20 {
    input: '',
    code: 'ERR_INVALID_URL'
  }
}
```

**Comment by yannick-aivayan** [comment]
In fact a simple change seems to fix the issue.  
Since it's only a feature detection it should be fine.  
I can come up with a PR if needed

```ts
export const supportsStreams = (() => {
    let duplexAccessed = false;
    let hasContentType = false;
    const supportsReadableStream = typeof globalThis.ReadableStream === 'function';
    if (supportsReadableStream) {
        hasContentType = new globalThis.Request('https://github.com/sindresorhus/ky', {
            body: new globalThis.ReadableStream(),
            method: 'POST',
            // @ts-expect-error - Types are outdated.
            get duplex() {
                duplexAccessed = true;
                return 'half';
            },
        }).headers.has('Content-Type');
    }
    return duplexAccessed && !hasContentType;
})();
```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ky/releases/tag/v0.31.3

**Comment by yannick-aivayan** [comment]
@sindresorhus Thanks a lot!
And congrats for you and the maintainers for this library!  
With fetch implemented on NodeJs it also works perfectly server-side now :)
