### ISSUE TITLE
TypeError: Cannot set property duplex of #<Request> which has only a getter

### ISSUE THREAD

**Issue by probablykasper** [sindresorhus/ky#467]
I'm getting this error when using ky server-side in SvelteKit:
```
handleNetworkError: TypeError: Cannot set property duplex of #<Request> which has only a getter
    at new Ky (file:///Users/k/dev/git/limey/node_modules/ky/distribution/core/Ky.js:86:33)
    at Function.create (file:///Users/k/dev/git/limey/node_modules/ky/distribution/core/Ky.js:111:20)
    at ky.<computed> (file:///Users/k/dev/git/limey/node_modules/ky/distribution/index.js:10:45)
    at Object.json (/src/lib/api-utils/fetcher.ts:10:26)
    at eval (/src/routes/api/domains/list/+server.ts:17:6)
    at requestHandler (/src/lib/api-utils/api.ts:39:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async render_endpoint (file:///Users/k/dev/git/limey/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:46:20)
    at async resolve (file:///Users/k/dev/git/limey/node_modules/@sveltejs/kit/src/runtime/server/index.js:238:17)
    at async respond (file:///Users/k/dev/git/limey/node_modules/@sveltejs/kit/src/runtime/server/index.js:292:20)
```

The same issue happens with ky-universal, so that's why I'm filing it here.

**Comment by madeleineostoja** [comment]
This also just popped up for me, however it also fails in prod. Is setting `request.duplex` still required, and should that work? Ie: is this a sveltekit issue or something Ky needs to patch?

**Comment by probablykasper** [comment]
It happens in production for me as well, was mistaken at first. Not sure if the issue lies with ky or sveltekit or both

**Comment by madeleineostoja** [comment]
It feels like a discrepancy between `fetch` on the client vs Node, since all my clientside ky requests are still fine, and I'm not using Sveltekit's `fetch` implementation, just plain Node endpoints.

**Comment by probablykasper** [comment]
I was running into the same error using ky-universal though, which should work with Node.js

**Comment by dummdidumm** [comment]
My guess is that the latest version of `undici` is responsible for this, marking the `duplex` property a read-only getter. I haven't confirmed this, but from looking at the changes and SvelteKit and the code in Ky this seems like the most probably cause.

**Comment by Talent30** [comment]
same here with node19

**Comment by MatthewNewland** [comment]
I am also getting this error :(

**Comment by jazoom** [comment]
Same error. Not using Svelte.

**Comment by chybisov** [comment]
I got this error while testing with jest v29 and node 19.

**Comment by Talent30** [comment]
@sindresorhus Could you tell us some clues?

**Comment by sindresorhus** [comment]
I looked at the Fetch specification and the property is indeed marked as readonly. So Ky is doing the wrong thing here.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ky/releases/tag/v0.33.1
