### ISSUE TITLE
Getting error while trying to use KY to fetch data in NEXTJS 13 Server APIs 'TypeError: Cannot construct a Request with a Request object that has already been used.'

### ISSUE THREAD

**Issue by FaizanShaikh45** [sindresorhus/ky#486]
Hi Guys,

Config:
```
KY Version: ^0.33.2
Node Version: 18.13.0
NextJS Version: latest (13)
React: 18.2.0
```

I'm trying to use KY to retrieve data from backend services. I'm using KY in the NextJS APIs folder to call down-stream services. However, I am receiving the error mentioned below. 

```
TypeError: Cannot construct a Request with a Request object that has already been used.
    at Object.fetch (node:internal/deps/undici/undici:14062:11)
    at async fn (webpack-internal:///(api)/./node_modules/ky/distribution/core/Ky.js:29:28)
    at async result.<computed> [as json] (webpack-internal:///(api)/./node_modules/ky/distribution/core/Ky.js:65:39)
    at async handler (webpack-internal:///(api)/./pages/api/user/recommended-user-list.ts:13:30)
    at async Object.apiResolver (folder/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async DevServer.runApi (folder/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (folder/node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (folder/node_modules/next/dist/server/router.js:253:36)
    at async DevServer.run (folder/node_modules/next/dist/server/base-server.js:384:29)
    at async DevServer.run (folder/node_modules/next/dist/server/dev/next-dev-server.js:741:20)
    at async DevServer.handleRequest (folder/node_modules/next/dist/server/base-server.js:322:20)
```

HTTP Client Code Ref: <img width="538" alt="image" src="https://user-images.githubusercontent.com/51155658/214694127-813af5e9-b6ae-4734-a9a5-0cd4605cca92.png">

The structure I'm attempting to set up for the http client is seen above. So I'm trying to create an HTTP client and passing it to the service as arguments to the function, and then with that client service is calling downstream APIs to get data.

Service Code Ref: 
<img width="243" alt="image" src="https://user-images.githubusercontent.com/51155658/214695290-1fdb8c05-9a4c-4698-8d45-1553bfa12007.png">

It works perfectly with NextJS 12, however when I try to implement it with NextJS 13, I get this problem. Could someone please assist me with this? 
Thanks

**Comment by panudetjt** [comment]
Have you figured it out ? 

My assumption is because nextjs is polyfill the native fetch with their own version of fetch.

**Comment by Talent30** [comment]
The fetch in NextJS behaves differently to the native fetch.

**Comment by Talent30** [comment]
I can reproduce this, maybe need to raise an issue on next.js side

**Comment by AlexisWalravens** [comment]
I also encountered this issue, I tried with just the native NodeJS fetch (polyfilled by Next) and I don't have the issue with just fetch.

**Comment by vladly** [comment]
I also faced this problem.

**Comment by belgattitude** [comment]
Have you tried on node 18 ?

**Comment by lcdss** [comment]
Same problem here. I'll probably use just fetch for now.

**Comment by mabdullahadeel** [comment]
I am also having troubles getting `ky` to work in nextjs server actions/components

In my case, it does make request but the json payload is not attached to the request. Using `fetch` solved the issue. So I guess it's something related to `ky` polyfill.

**Comment by sholladay** [comment]
Please try awaiting the response before calling `.json()` and tell me if that fixes it or not.

Before:
```js
return httpClient
    •post ("test/test", {
        json: {
            test: params. test,
        }
    })
    .json()
```

After:

```js
const response = await httpClient
    •post ("test/test", {
        json: {
            test: params. test,
        }
    });

return response.json();
```

**Comment by sindresorhus** [comment]
I believe this has been fixed in later versions. If it's still an issue on the latest version, let me know and I will reopen.
