### ISSUE TITLE
Aggregated error on server side.

### ISSUE THREAD

**Issue by nihanmubashshir** [sindresorhus/ky#617]
Hello,
I am certain that this is not a consistent issue. I have been using ky in serveral projects. But this particular issue has been seen only on one of them and it has been working before but not sure why it's not working now.

I am using nextjs for an app. And using ky to fetch few things in the middleware. I am facing an aggregated error. Please note that ky works on the browser just fine.

Here is the function in question:
```js
// lives in a separate file
export const serverKy = () => {
  // Forwarding cookies
  const cookie = cookies().toString()
  return ky.create({
    headers: {
      cookie,
    },
    prefixUrl: envUrl as any,
  })
}

const getUserInfo = async (request: NextRequest): Promise<User | undefined> => {
  try {
    const user: User = await serverKy().get("api/users/my-infos").json();
    if (user) {
      return user
    }
  } catch (e) {
    console.error(e)
    return
  }
}
```

```
⨯ unhandledRejection: Error: fetch failed
    at context.fetch (project-root/node_modules/next/dist/server/web/sandbox/context.js:272:38)
    at eval (webpack-internal:///(middleware)/./node_modules/ky/distribution/utils/timeout.js:17:14)
    at new Promise (<anonymous>)
    at timeout (webpack-internal:///(middleware)/./node_modules/ky/distribution/utils/timeout.js:9:12)
    at Ky._fetch (webpack-internal:///(middleware)/./node_modules/ky/distribution/core/Ky.js:267:77)
    at function_ (webpack-internal:///(middleware)/./node_modules/ky/distribution/core/Ky.js:30:37)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at process.processTimers (node:internal/timers:519:7)
    at async Ky._retry (webpack-internal:///(middleware)/./node_modules/ky/distribution/core/Ky.js:227:20) {
  cause: Error: AggregateError
      at makeNetworkError (eval at requireWithFakeGlobalScope (project-root/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:7365:35)
      at httpNetworkFetch (eval at requireWithFakeGlobalScope (project-root/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:12125:16)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async httpNetworkOrCacheFetch (eval at requireWithFakeGlobalScope (project-root/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:12000:33)
      at async httpFetch (eval at requireWithFakeGlobalScope (project-root/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11837:37)
      at async schemeFetch (eval at requireWithFakeGlobalScope (project-root/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11762:18)
      at async eval (eval at requireWithFakeGlobalScope (project-root/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11635:20)
      at async mainFetch (eval at requireWithFakeGlobalScope (project-root/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11625:20)
}
```

OS: majnaro
Node version: v22.4.1
Also using yarn.

I am trying to figure this out, but any recommendations would be highly appreciated.

**Comment by nihanmubashshir** [comment]
Never mind, found the issue!!.. Someone made a change :cry:
