### ISSUE TITLE
Next.js Build Fails with 400 Bad Request After 202 Pages When Using ky, Works with fetch

### ISSUE THREAD

**Issue by MhL5** [sindresorhus/ky#646]
I'm encountering an issue during the build process of my Next.js app. Everything works perfectly in development mode (next dev), but when I try to build the application (next build), I consistently get an error after successfully generating around 202 static pages.

The error occurs when using ky to fetch markdown files for blog posts. The first page that typically fails is page 202, with the error message showing a 400 Bad Request. However, when I switch to fetch for the same API call, the build completes successfully without any issues.

## Error Log
```js
HTTPError: Request failed with status code 400 Bad Request: GET http://blog.vsim.space/posts/markdown/2.md
    at o (D:\-code\work\vsim\.next\server\chunks\2576.js:1:82169)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async T._retry (D:\-code\work\vsim\.next\server\chunks\2576.js:1:85858)
    at async i.<computed> [as text] (D:\-code\work\vsim\.next\server\chunks\2576.js:1:82789)
    at async l (D:\-code\work\vsim\.next\server\app\[lang]\(with-navigation)\blog\page.js:1:17639)
    at async u (D:\-code\work\vsim\.next\server\app\[lang]\(with-navigation)\tips\[tipSlug]\page.js:1:6941)
Generating static pages (208/228)  [    ]
Error occurred prerendering page "/tr/tips/vsim-tip-code-delivery". Read more: https://nextjs.org/docs/messages/prerender-error
```

The issue arises when using ky:
```js
const md = await ky
    .get(data.markdown_path, { cache: "no-store", timeout: 5 * 60 * 1000 })
    .text();
```
When I switch to fetch, the build succeeds without any issues:
```js
const resMd = await fetch(data.markdown_path);
const md = await resMd.text();
```

**Comment by sholladay** [comment]
Can you try to log the error's response body?

**Comment by MhL5** [comment]
```
r [HTTPError]: Request failed with status code 400 Bad Request: GET http://blog.space/posts/markdown/2.md
    at o (D:\-code\work\vsim\.next\server\chunks\2576.js:1:82169)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async T._retry (D:\-code\work\vsim\.next\server\chunks\2576.js:1:85858)
    at async i.<computed> [as text] (D:\-code\work\vsim\.next\server\chunks\2576.js:1:82789)
    at async l (D:\-code\work\vsim\.next\server\app\[lang]\(with-navigation)\blog\[blogSlug]\page.js:1:11558)
    at async u (D:\-code\work\vsim\.next\server\app\[lang]\(with-navigation)\tips\[tipSlug]\page.js:1:6941) {
  response: Response {
    status: 400,
    statusText: 'Bad Request',
    headers: Headers {
      server: 'cloudflare',
      date: 'Fri, 25 Oct 2024 13:51:53 GMT',
      'content-type': 'text/html',
      'content-length': '253',
      connection: 'close',
      'cf-ray': '-'
    },
    body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
    bodyUsed: false,
    ok: false,
    redirected: false,
    type: 'basic',
    url: 'http://blog.space/posts/markdown/2.md'
  },
  request: Request {
    method: 'GET',
    url: 'http://blog.space/posts/markdown/2.md',
    headers: Headers { accept: 'text/*' },
    destination: '',
    referrer: 'about:client',
    referrerPolicy: '',
    mode: 'cors',
    credentials: 'same-origin',
    cache: 'default',
    redirect: 'follow',
    integrity: '',
    keepalive: false,
    isReloadNavigation: false,
    isHistoryNavigation: false,
    signal: AbortSignal { aborted: false }
  },
  options: {
    method: 'GET',
    headers: Headers {},
    hooks: {
      beforeRequest: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: []
    },
    prefixUrl: '',
    retry: {
      limit: 2,
      methods: [Array],
      statusCodes: [Array],
      afterStatusCodes: [Array],
      maxRetryAfter: Infinity,
      backoffLimit: Infinity,
      delay: [Function: delay]
    },
    throwHttpErrors: true,
    timeout: 10000,
    fetch: [Function: bound c] AsyncFunction,
    signal: AbortSignal { aborted: false },
    duplex: 'half'
  }
}
```
this is the error 
weird thing is that it works with native fetch but not with ky

**Comment by Antoine-Regembal** [comment]
Hi,

I'm facing the same issue of a request working fine with fetch but failing with Ky IF I extend ky and use things like "prefixUrl" or "beforeRequest" hook

So I'm not sure what make the error happen but there is strange behavior here

**Comment by sholladay** [comment]
I would suggest checking to see if one of the requests is repeated. That might explain why the server complains about the `id` even if it looks good.

**Comment by sindresorhus** [comment]
Closing as there is not much we can do without a failing tests, and we already had multiple fixes for Next.js compatibility since this.
