### ISSUE TITLE
Orphan ReadableStream remaining after retry

### ISSUE THREAD

**Issue by HaidongPang** [sindresorhus/ky#650]
Cloudflare workers raise the following warning:
```
A ReadableStream branch was created but never consumed. Such branches can be created, for instance, by calling the tee() method on a ReadableStream, or by calling the clone() method on a Request or Response object. If a branch is created but never consumed, it can force the runtime to buffer the entire body of the stream in memory, which may cause the Worker to exceed its memory limit and be terminated. To avoid this, ensure that all branches created are consumed.

 * Unused stream created:
    at Ky._fetch (file:///....../node_modules/ky/source/core/Ky.ts:303:30)
    at function_ (file:///....../node_modules/ky/source/core/Ky.ts:38:28)
    at async Ky._retry (file:///....../node_modules/ky/source/core/Ky.ts:256:11)
```

The request object that was cloned in advance for retry preparation still remains after returning a response that does not require a retry.

```typescript
export class Ky {
	protected async _fetch(): Promise<Response> {
		......

		// Cloning is done here to prepare in advance for retries
		const mainRequest = this.request;
		this.request = mainRequest.clone();

		if (this._options.timeout === false) {
			return this._options.fetch(mainRequest, nonRequestOptions);
		}

		return timeout(mainRequest, nonRequestOptions, this.abortController, this._options as TimeoutOptions);
	}
}
```

Related to :[#648](https://github.com/sindresorhus/ky/issues/648)

**Comment by HaidongPang** [comment]
Canceling the Request ReadableStream prepared for retry after determining that the current request does not need to be retried can ensure memory safety.

**Comment by work-in-progress-danny** [comment]
https://github.com/sindresorhus/ky/pull/661 might not have fixed this. I'm on v1.7.4 and getting this error

```js
const response = await ky.post("...url...", {
  throwHttpErrors: false,
  retry: { limit: 0 },
  headers: {
    "Content-Type": "application/json",
    Authorization: `Bearer ${ctx.env.API_KEY}`,
  },
  json: <...data...>,
})

if (!response.ok) {
  console.error(response.statusText)
  return
}

const jsonResponse = await response.json()
```

```
ReadableStream branch was created but never consumed. Such branches can be created, for instance, by calling the tee() method on a ReadableStream, or by calling the clone() method on a Request or Response object. 
If a branch is created but never consumed, it can force the runtime to buffer the entire body of the stream in memory, which may cause the Worker to exceed its memory limit and be terminated.
To avoid this, ensure that all branches created are consumed.

 * Unused stream created:
    at Ky._fetch (file://..../node_modules/ky/source/core/Ky.ts:305:30)
    at function_ (file://..../node_modules/ky/source/core/Ky.ts:38:28)
    at async <function> (file://..../function.ts:30:20)

```
